### PR TITLE
[#42] add azure openai (test needed)

### PR DESCRIPTION
**Pull request by jekalmin**
## Issue
- #42

## Objective
- support azure openai

## Note
- test needed (Since I don't have azure openai API, it is not tested yet)

### CODE REVIEW

**Comment by AsafMah** [comment]
It doesn't work sadly as-is, but I did get it to work:

1. Validation - sadly the azure openai doesn't have the "models" endpoint, so validation doesn't work. I had to change the code to skip it. Maybe add a checkbox to skip validation?
2. Azure openai when sending the chat needs the "engine" parameter instead of the "model" parameter, changingthis caused it to work :)
3. This I can't test because I don't have a regular openai account - but I think you shouldn't pass this parameter if it's not azure (or at least make it not mandatory). A good default to azure BTW is 2023-07-01-preview

**Comment by jekalmin** [comment]
Thanks for a feedback!
I will apply changes you listed and let you know again!

**Comment by AsafMah** [comment]
> Thanks for a feedback! I will apply changes you listed and let you know again!
> 
> One question I have is following:
> 
> > 3. This I can't test because I don't have a regular openai account - but I think you shouldn't pass this parameter if it's not azure (or at least make it not mandatory)
> 
> Which parameter shouldn't be passed?

Sorry - I meant "api version"

**Comment by jekalmin** [comment]
@AsafMah 
Can you try this again?
I added "skip authentication" and "model_key" for validation and engine parameter.
If you want me to release this in beta version, feel free to tell me.

skip authentication | model key
--|--
 |

**Pull request merged**
