### PR TITLE
feat(translation): Add fr translation

### PR DESCRIPTION
**Pull request by shiipou**

### CODE REVIEW

**Review by jekalmin — APPROVED** [review]
Thanks for your contribution.
It will be released in the next version.

**Comment by shiipou** [comment]
> Thanks for your contribution. It will be released in the next version.
@jekalmin 

It can be cool to add to a new release openai's TTS and STT API to add recognition on low end device using the API.

https://platform.openai.com/docs/guides/text-to-speech
https://platform.openai.com/docs/guides/speech-to-text

**Comment by jekalmin** [comment]
It's a nice feature!
I'm not certain whether it's the feature that this integration should implement or not.

**Comment by shiipou** [comment]
> I just found out that tts integration already exists.
> 
> [sfortis/openai_tts](https://github.com/sfortis/openai_tts)

Oh ok, Thanks for that

**Pull request merged**
