### PR TITLE
Function spec example for say_tts

### PR DESCRIPTION
**Pull request by danielp370**
A flexible say tts example.  This allows the LLM to pass in any tts entity so it can direct the message to where it is needed.

### CODE REVIEW

**Comment by Scags104** [comment]
Question on this, and i know its not its intended purpose but could this be modified and utilized in a way that my input device and output device were separate entities? 

Example:
Ask home assistant satellite with no external speaker a question
Home assistant pipeline using extended openai processes
Function always called to export response to specific speaker based on area of input satellite

Let me know your thoughts

**Comment by jekalmin** [comment]
If this [PR](https://github.com/jekalmin/extended_openai_conversation/pull/172) is merged, you can use input `device_id` in service template. In this way, it seems you will be able to conditionally select a output speaker.

**Comment by Scags104** [comment]
> If this [PR](https://github.com/jekalmin/extended_openai_conversation/pull/172) is merged, you can use input `device_id` in service template. In this way, it seems you will be able to conditionally select a output speaker.

sure but how would i grab the response back that open AI is sending?

**Comment by jekalmin** [comment]
Currently, as far as I know, Assist pipeline doesn't support respond to another speaker.
Although I haven't tried, this will be a workaround that it pretends to be output speaker but it isn't in reality.
Hence, the response will be lost.

**Pull request merged**
